### ISSUE TITLE
First test failing due to missing allocator file

### ISSUE THREAD

**Issue by HarrisonKeeling** [usf-cs326-sp19/P3-Tests#1]
What is the purpose of removing the allocator file before checking if it exists?

https://github.com/usf-cs326-sp19/P3-Tests/blob/9485739424bc469d922ccb225c6720943f58694b/01-Unix-Utilities-1.sh#L6

**Comment by HarrisonKeeling** [comment]
This has been fixed in https://github.com/usf-cs326-sp19/P3-Tests/commit/31d7c9f3ef7e9933397ef682921ee1b20fa55671

**Comment by malensek** [comment]
Thanks... a little debugging code got left in :-)
