### ISSUE TITLE
Test 3 includes free'd memory block

### ISSUE THREAD

**Issue by HarrisonKeeling** [usf-cs326-sp19/P3-Tests#2]
I noticed that Test 3 shouldn't have [Memory Block with ID 3](https://github.com/usf-cs326-sp19/P3-Tests/blob/31d7c9f3ef7e9933397ef682921ee1b20fa55671/03-Basic-First-Fit-1.sh#L7) in the memory output because I believe that the allocations-1 file [frees that particular block](https://github.com/usf-cs326-sp19/P3-Tests/blob/31d7c9f3ef7e9933397ef682921ee1b20fa55671/progs/allocations-1.c#L14).

**Comment by malensek** [comment]
That *should* be okay; basically if a block is freed but hasn't been reused it should still show up in the output. That's why allocation 1 doesn't show up (it has been replaced with allocation 6)
